# X=2
# print(X,type(X))
# y=5.3
# print(y,type(y))
# l=("list;1")
# # print(l,type(l))
# a=None
# print(a,type(a))
# m=True
# print(m,type(m))
# n=False
# print(n,type(n))
# a=5
# b='hello'
# print("the value of a is",a)
# print("the value of b is",b)
# # print("the value of b is"+b)
# a=5;b="hello";c=4.2
# print(a,type(a))
# print(b,type(b))
# print(c,type(c))
# print("the value of a is",a)
# print("the value of c is",c)
# print("the value of b is"+b)
# a="python"
# b='3.9.7'
# print(a+b)
# # print(a,b)
# print("hello python")
# print("hello","python")
# a="hello"
# b="python"
# print(a,b)
print("hello"+''+"python")


