# a="hello" ;b="python"
# print(a,b,sep=" ")
# print(a,b,sep="_")
# print(a,b,sep="+")
# print("hello","world",sep="")
# print("hello","world",sep=" ")
# print("hello","world",sep=".")
# print("hello","world",sep="_")
# print("hello","world",sep="e")
# print("moto","edge20",sep="")
# print("moto","edge",sep=" ")
# print("moto","edge",sep=".")
# print("moto","edge",sep="_")
# print("hello",end="")
# print("python")
# print("hello",end=".")
# print("hello",end="_" )
# print("python",end=" ")
# print("hi")
# print("core","pyuthon",sep="_")
# print("core","python",end="" "hello")
# print("core","python",end="_"'3')
# print("core","python",sep="_""hello")
# print("core","python",end="" "hello")
# print("core","python",end="-"'3')
# print("core","python",sep="",end='hello')
# print("core","python",sep="_",end="hello")
# print("core","python",sep="",end='3')
print("core","python",end="hello",sep=" ")