print('hello /nworld')
print("hello py/'thon")
# print('hello pyt/"hon')
# print('f:\Uatch-9-15-am')
# print("c:// user //josh//DOUNLOADS")
# print('\u0001')
# print('\u0002')
# print('\u0003')
# # print('\U005')
# print('\u0006')
# print('\u0007')
# print("\N{rollang on the floor laughing}")
# print("\N {grinning face}")
# print('hello \divya')
# print('hello\sohail')
# print('hello\\nayum')
# # print("hello\tworld")
# print("\thelloworld")
# print("hello\t" "world")
# print("hello \t"   "world")
# print("hello \t  world")
# print("py\ron")
# print("pyth\ron")
# print("hello\rpyp5tg")
print("my name is\r  allu arjun")
